<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Data Scope Drivers
    |--------------------------------------------------------------------------
    | Mapping string driver from database to its implementation class.
    | The package's built-in drivers are already available. You can add your own
    | custom drivers below.
    |
    */
    'drivers' => [
        'unrestricted' => \Bpma\DataScope\Drivers\UnrestrictedDriver::class,

        // Custom Application Driver
        // 'subordinate' => \App\DataScopes\Drivers\SubordinateDriver::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Table Names
    |--------------------------------------------------------------------------
    | Table names that will be generated by this package's migration.
    |
    */
    'table_names' => [
        'data_scopes' => 'data_scopes',
        'model_has_data_scopes' => 'model_has_data_scopes',
    ],
];